<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cetak QR Code - {{ $cabang->nama_cabang }}</title>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <style>
        :root {
            --blue:       #2563EB;
            --blue-dark:  #1D4ED8;
            --blue-soft:  #EFF6FF;
            --slate-900:  #111827;
            --slate-600:  #4B5563;
            --slate-400:  #9CA3AF;
            --slate-200:  #E5E7EB;
            --slate-100:  #F3F4F6;
            --white:      #FFFFFF;
            --shadow-lg:  0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1);
        }

        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }

        body {
            font-family: 'Inter', sans-serif;
            background-color: var(--slate-100);
            color: var(--slate-900);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px;
        }

        .qr-wrapper {
            background: var(--white);
            border-radius: 24px;
            box-shadow: var(--shadow-lg);
            width: 100%;
            max-width: 480px;
            overflow: hidden;
            border: 1px solid var(--slate-200);
        }

        .qr-header {
            background: var(--white);
            padding: 32px 32px 20px;
            text-align: center;
            border-bottom: 1px dashed var(--slate-200);
        }

        .brand-name {
            font-size: 24px;
            font-weight: 800;
            color: var(--blue);
            letter-spacing: -0.5px;
            margin-bottom: 4px;
        }

        .cabang-name {
            font-size: 18px;
            font-weight: 700;
            color: var(--slate-900);
            margin-bottom: 6px;
        }

        .cabang-code {
            display: inline-block;
            background: var(--blue-soft);
            color: var(--blue-dark);
            padding: 4px 12px;
            border-radius: 50px;
            font-size: 13px;
            font-weight: 700;
            font-family: monospace;
            letter-spacing: 1px;
        }

        .qr-body {
            padding: 40px 32px;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        /* Container for the QR Code generated by JS */
        .qr-frame {
            background: var(--white);
            padding: 16px;
            border: 2px solid var(--slate-200);
            border-radius: 16px;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);
            margin-bottom: 24px;
            display: flex;
            align-items: center;
            justify-content: center;
            width: 250px;
            height: 250px;
            position: relative;
        }

        /* Loading indicator before JS renders */
        .qr-loader {
            position: absolute;
            font-size: 14px;
            font-weight: 600;
            color: var(--slate-400);
            animation: pulse 1.5s infinite;
        }

        @keyframes pulse {
            0% { opacity: 0.5; }
            50% { opacity: 1; }
            100% { opacity: 0.5; }
        }

        /* Generated image by JS */
        #qrcode img, #qrcode canvas {
            width: 100% !important;
            height: 100% !important;
            display: block;
            border-radius: 4px;
        }

        .qr-instruction {
            text-align: center;
            font-size: 14px;
            line-height: 1.6;
            color: var(--slate-600);
            font-weight: 500;
            max-width: 300px;
        }

        .qr-instruction strong {
            color: var(--slate-900);
        }

        .qr-footer {
            background: var(--slate-50);
            padding: 24px 32px;
            text-align: center;
            border-top: 1px solid var(--slate-200);
        }

        .btn-print {
            background: linear-gradient(135deg, var(--blue) 0%, var(--blue-dark) 100%);
            color: var(--white);
            border: none;
            padding: 14px 28px;
            border-radius: 12px;
            font-size: 15px;
            font-weight: 700;
            font-family: 'Inter', sans-serif;
            cursor: pointer;
            box-shadow: 0 4px 12px rgba(37, 99, 235, 0.25);
            transition: all 0.2s ease;
            width: 100%;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            gap: 8px;
        }

        .btn-print:hover {
            transform: translateY(-2px);
            box-shadow: 0 6px 16px rgba(37, 99, 235, 0.35);
        }

        .btn-print:active {
            transform: translateY(0);
        }

        .btn-print svg {
            width: 20px;
            height: 20px;
        }

        /* PRINT STYLES */
        @media print {
            body {
                background: white;
                padding: 0;
                align-items: flex-start;
                justify-content: center;
            }
            .qr-wrapper {
                box-shadow: none;
                border: none;
                max-width: none;
                width: 100%;
                border-radius: 0;
            }
            .qr-header {
                padding: 40px 20px 20px;
            }
            .qr-body {
                padding: 40px 20px;
            }
            .qr-footer {
                display: none;
            }
            .qr-frame {
                border-color: #000;
                box-shadow: none;
                width: 350px;
                height: 350px;
            }
        }

        /* RESPONSIVE */
        @media (max-width: 480px) {
            body { padding: 16px; }
            .qr-wrapper { border-radius: 20px; }
            .qr-header { padding: 24px 20px 16px; }
            .qr-body { padding: 32px 20px; }
            .qr-frame { width: 220px; height: 220px; }
        }
    </style>
</head>
<body>

    <div class="qr-wrapper">
        <div class="qr-header">
            <div class="brand-name">PresensiGPS</div>
            <div class="cabang-name">{{ $cabang->nama_cabang }}</div>
            <div class="cabang-code">KODE: {{ $cabang->kode_cabang }}</div>
        </div>
        
        <div class="qr-body">
            <div class="qr-frame">
                <div class="qr-loader" id="loader">Generating...</div>
                <div id="qrcode"></div>
            </div>
            
            <p class="qr-instruction">
                Arahkan kamera dari menu <strong>Scan QR</strong> pada aplikasi PresensiGPS untuk mencatat kehadiran di lokasi ini.
            </p>
        </div>

        <div class="qr-footer">
            <button class="btn-print" onclick="window.print()">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <polyline points="6 9 6 2 18 2 18 9"></polyline>
                    <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"></path>
                    <rect x="6" y="14" width="12" height="8"></rect>
                </svg>
                Cetak Halaman Ini
            </button>
        </div>
    </div>

    <!-- Minimalist JS QR Code Library -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            // Sembunyikan tulisan loading
            document.getElementById('loader').style.display = 'none';
            
            // Generate QR Code secara instan di sisi klien
            var qrCodeElement = document.getElementById("qrcode");
            var qrText = "{{ $cabang->kode_cabang }}";
            
            new QRCode(qrCodeElement, {
                text: qrText,
                width: 300,
                height: 300,
                colorDark : "#111827", // Var(--slate-900)
                colorLight : "#ffffff",
                correctLevel : QRCode.CorrectLevel.H
            });
        });
    </script>
</body>
</html>
